import streamlit as st
from PIL import Image

st.set_page_config(page_title="mBARq App", layout='wide',
                   page_icon=Image.open("images/image.png")
                   )
st.image("images/mbarq-logo.png")


def home_page():
    repo_url = "https://github.com/MicrobiologyETHZ/mbarq"
    docs_url = "https://mbarq.readthedocs.io/en/latest/"
    st.info(f""" 
    
    Transposon mutagenesis is a powerful technique that allows identification of bacterial fitness factors under 
   different environmental conditions. Recently, a number of studies have used barcoded transposon mutant libraries 
   to increase the throughput of the experiments. mBARq allows easy processing and analysis of barcoded mutant 
   libraries for any transposon construct. To learn more about analysis of barcoded sequencing data using mBARq, please read the [documentation]({docs_url}). This app allows exploration of data analyzed with [mBARq tool](
   {repo_url}). 
   
    """)
    map_url = 'https://mbarq.readthedocs.io/en/latest/mapping.html'
    st.markdown(f"""
  
    
    ## Pages:
    
    Below is a quick summary of each of the pages, visit each of the pages to browse example data set. 
    
    ### ⬆️ Data Upload 

    - On this page you can upload all of the data tables produced by `mbarq` command line tool. 
        
    ***
    
    ### 📍 Library Map 
    
    - Requires a `csv` file generated by [`mbarq map`]({map_url}) command. This file lists the insertion site of each barcode in your mutant library.  
    - This page allows you to visualize the insertions found in your library and provides some basic summary statistics. 
        
    
    """)

    st.markdown("""
    ***
    
    ### 📈 Exploratory Data Analysis
    
    - Requires a `csv` file with barcode counts for each sample. This file is generated by `mbarq count` and `mbarq merge` commands.
    - Also requires a `csv` file describing the experimental design. (sample data file)
    - This page generates an interactive PCA plot and barcode abundance plots for genes of interest.
        
    """)

    st.markdown("""
        
    ***
    
    ### 📊 Differential Abundance
    - Requires a `csv` file produced by `mbarq analyze` command. This file lists log fold changes (LFC) and false discover rates (FDRs) for each gene in the library.
    - This page allows you to look at the 'hits' and create heatmaps of LFCs for genes of interest.

    ***
    
    ### 🧶 STRING  
    - Requires a `csv` file produced by `mbarq analyze` command. This file lists log fold changes (LFC) and false discover rates (FDRs) for each gene in the library.
    - This page allows you to perform functional analysis via STRING-db.
    ***
    
    ### 🥚 KEGG
    - Requires a `csv` file produced by `mbarq analyze` command. This file lists log fold changes (LFC) and false discover rates (FDRs) for each gene in the library.
    - This page allows you to visualize the results in the context of KEGG metabolic maps.
        """)


home_page()
