import streamlit as st
import jinja2

def app():
    url = "https://github.com/MicrobiologyETHZ/mbarq"
    st.markdown(f""" 

    This app allows exploration of data processed and analyzed with [mBARq tool]({url}). It is currently in beta!
 
    ### Options:
    
    1. **Library Map**: 
    
        - Allows you to visualize the insertions found in your library and provides some basic summary statistics.
        - Requires mapping file generated by `mbarq map` command

        
    2. **Exploratory Analysis**: 
        
        - Generates an interactive PCA plot
        - Generates barcode abundance plots for genes of interest
        - Requires merged count file generated by `mbarq count` and a the same sample data file used for the analysis
        
        
    3. :hourglass: **Differential Abundance Results**
    
        - Currently under development
        - Visualize differential abundance results for all genes or specific KEGG pathways
        - Draw heatmaps of log fold changes across the conditions for specific KEGG pathways
    
    
    4.  :soon: **Metabolic Pathway Visualization** 
    
        - Coming soon
        - Overlay gene log fold changes on metabolic maps 
    
    
    """)