links:
  mbarq_paper: https://doi.org/10.1093/bioinformatics/btae078
  mbarq_repo: https://github.com/MicrobiologyETHZ/mbarq
  nguyen_2020: https://doi.org/10.1016/j.chom.2020.04.013
  nguyen_2024:
  docs_url: https://mbarq.readthedocs.io/en/latest/
  mapping_url: https://mbarq.readthedocs.io/en/latest/mapping.html
  counting_url: https://mbarq.readthedocs.io/en/latest/counting.html
  analysis_url: https://mbarq.readthedocs.io/en/latest/analysis.html
  salmonella_workflow: https://mbarq.readthedocs.io/en/latest/salmonella.html
  string_database: https://string-db.org/
  kegg_database: https://www.genome.jp/kegg/

library_map:
  fixed_column_names:
    barcode_col: barcode
    abundance_col: abundance_in_mapping_library
    insertion_site_col: insertion_site
    chr_col: chr
    distance_col: distance_to_feature
    library_col: library
  optional_column_names:
    gene_start_col: gene_start
    gene_end_col: gene_end
    strand_col: gene_strand
    percentile_col: percentile

eda:
  fixed_column_names:
    barcode_col: barcode
    gene_name_col: Gene Identifier
    name_col: name
    sample_id_col: sample_id

results:
  fixed_column_names:
    lfc_col: LFC
    fdr_col: neg_selection_fdr
    fdr_col2: pos_selection_fdr
    contrast_col: contrast
    library_col: library





